# Setting: general.entity.skip-ticks Default: true # If enabled, allows the default entity tick skip feature when no players are near.
# Setting: general.tileentity.skip-ticks Default: true # If enabled, turns on tileentity tick skip feature when no players are near.
# Setting: general.tileentity.prevent-invalid-updates Default: true # Used to determine if a tileentity should tick and if not the TE is added to a ban list. Note: This should help improve performance.
# Setting: general.tileentity.debug.can-update-warning Default: false # Set true to detect which tileentities should not be ticking.
# Setting: general.tileentity.debug.inventory-warning Default: false # Set true to detect which tileentities with inventory failed to detect size for Bukkit's InventoryType enum. Note: This may detect a false-positive.
# Setting: general.tileentity.debug.place-warning Default: false # Warn when a mod requests tile entity from a block that doesn't support one

general:
  entity:
    skip-ticks: true
  tileentity:
    skip-ticks: true
    prevent-invalid-updates: true
    debug:
      can-update-warning: false
      inventory-warning: false
      place-warning: false
world:
  normal:
    keep-world-loaded: true
  nether:
    keep-world-loaded: true
    enabled: true
  the_end:
    keep-world-loaded: false
    enabled: true
plugin:
  default:
    debug: false
    remap-nms-v1_7_R4: true
    remap-nms-v1_7_R3: true
    remap-nms-v1_7_R1: true
    remap-nms-v1_6_R3: true
    remap-nms-v1_5_R3: true
    remap-nms-pre: false
    remap-obc-v1_7_R4: true
    remap-obc-v1_7_R3: true
    remap-obc-v1_7_R1: true
    remap-obc-v1_6_R3: true
    remap-obc-v1_5_R3: true
    remap-obc-pre: false
    global-inheritance: true
    plugin-inheritance: true
    remap-reflect-field: true
    remap-reflect-class: true
    remap-allow-future: false
    guava-version: 10
    custom-class-loader: true
  spark:
    guava-version: 17
entity:
  default:
    net-minecraft-entity-item-EntityMinecartChest:
      tick-no-players: false
      never-ever-tick: false
      tick-interval: 1
    net-minecraft-entity-item-EntityItem:
      tick-no-players: false
      never-ever-tick: false
      tick-interval: 1
    net-minecraft-entity-passive-EntityPig:
      tick-no-players: false
      never-ever-tick: false
      tick-interval: 1
    net-minecraft-entity-passive-EntityCow:
      tick-no-players: false
      never-ever-tick: false
      tick-interval: 1
    net-minecraft-entity-passive-EntityWolf:
      tick-no-players: false
      never-ever-tick: false
      tick-interval: 1
tileentity:
  default:
    net-minecraft-tileentity-TileEntityChest:
      tick-no-players: false
      tick-interval: 1
    net-minecraft-tileentity-TileEntityMobSpawner:
      tick-no-players: false
      tick-interval: 1
